list=["Ankit,Aman,Sourabh,Niket,Sumit,Shreeharsh"]
#list.reverse()
#list.clear()
#b=list.copy()
#print(b)
#list.reverse()
#list.insert(0,"Madhushankar")
#list.extend('helloji')
a=2,5,7,8,7,7
#a.sort()
#print(a)
#print(list)
print(min(a))